#    AI-CLI Simplifying AI Experiments
#    Copyright (C) 2022  Marcel Arpogaus, Julian Jandeleit
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
version: '3'

services:
  db:
    image: postgres:alpine
    container_name: aiclidb
    restart: always
    volumes:
      - ${MLFLOW_DATA}/pgdata:/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /pgdata
    networks:
      - mlflow_bridge
  server:
    image: ai-cli/${USER}:mlflow
    user: $DOCKER_USER
    container_name: ${USER}-mlflow-server
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --backend-store-uri
      - postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@aiclidb:5432/${POSTGRES_DB}
      - --default-artifact-root
      - file:///mlruns
    volumes:
      - ${MLFLOW_DATA}:/mlruns
      - /etc/ai-cli/hooks:/etc/ai-cli/hooks:ro
    environment:
      VIRTUAL_HOST: ${USER}-mlflow.${URLNAME}
      VIRTUAL_PORT: ${MLFLOWPORT}
      SSL_POLICY: Mozilla-Modern
      HSTS: 'max-age=31536000; includeSubDomains; preload'
      CERT_NAME: shared
    networks:
      - mlflow_bridge
      - proxy_net
    depends_on:
      - db

networks:
  mlflow_bridge:
    external: true
    name: ${USER}_mlflow_bridge
  proxy_net:
    external: true
