name: Build
on: [push]
jobs:
   Install:
      runs-on: ubuntu-latest
      steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Install AI-CLI
         run: |
           sudo make install
       - run: echo "Job status ${{ job.status }}"
