name: test-ci
on: [push]
jobs:
   test-ci:
      runs-on: ubuntu-latest
      steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Install AI-CLI
         run: |
           sudo make install && source /etc/environment
       - name: Execute Tests      
         id: exec-tests 
         run: |
           ./run-tests.sh
