name: test-ci
on: [push]
jobs:
   test-ci:
      runs-on: ubuntu-latest
      steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Install AI-CLI
         run: |
           sudo make install && source /etc/environment
       - name: Execute Tests      
         id: exec-tests 
         run: |
           echo "::set-output name=test-out::$(./run-tests.sh 2>&1 )"
       - name: Print Test Output
         run: echo "{{steps.exec-tests.outputs.test-out}}"
