name: test-ci
on: [push]
jobs:
   test-ci:
      runs-on: ubuntu-latest
      steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Setup Prerequisites for Test
         run: sudo ./install-prerequisites-manually.sh && sudo ./setup-for-tests.sh
       - name: Install AI-CLI
         run: |
           sudo make install && source /etc/environment
       - name: Execute Tests      
         id: exec-tests 
         run: |
           ./run-tests.sh 1> stdout.txt 2> stderr.txt
         continue-on-error: true
       - name: show stdout
         run: cat stdout.txt
       - name: show stderr
         run: cat stderr.txt
       - name: check on failures
         if : steps.exec-tests.outcome != 'success'
         run: exit 1
